sudo: false
dist: trusty
language: cpp

addons:
  apt:
    packages:

matrix:
  include:

    # GCC 9
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - CMAKE_OPTNS="-D CMAKE_BUILD_TYPE=Debug"
      install:    
        - mkdir $HOME/usr
        - export PATH="$HOME/usr/bin:$PATH"
        # - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
        - wget https://cmake.org/files/v3.17/cmake-3.17.0-Linux-x86_64.sh
        # - chmod +x cmake-3.7.2-Linux-x86_64.sh
        - chmod +x cmake-3.17.0-Linux-x86_64.sh
        - ./cmake-3.17.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mdkir -p build
  - cd build
  - cmake $CMAKE_OPTNS ..
  # - cmake --build . -- -j2 
  - make
  - ./mytest
  - ctest -j2 --output-on-failure

after_success:
  # Creating report
  # - cd ${TRAVIS_BUILD_DIR}
  # # capture coverage info
  # - lcov --directory . --capture --output-file coverage.info 
  # # filter out system and catch headers
  # - lcov --remove coverage.info '/usr/*' 'tests/catch.hpp' --output-file coverage.info 
  # # debug info
  # - lcov --list coverage.info 
  # # Uploading report to CodeCov
  # - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
