sudo: false
dist: trusty
language: cpp

addons:
  apt:
    packages:

matrix:
  include:

    # GCC 9
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - CMAKE_OPTNS="-D Template_ENABLE_COVERAGE:BOOL=TRUE
                       -D CMAKE_BUILD_TYPE=Debug"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake $CMAKE_OPTNS .
  - cmake --build . -- -j2 
  - ctest -j2 --output-on-failure

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info 
  # filter out system and catch headers
  - lcov --remove coverage.info '/usr/*' 'tests/catch.hpp' --output-file coverage.info 
  # debug info
  - lcov --list coverage.info 
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
