sudo: false
dist: trusty
language: cpp

addons:
  apt:
    packages:

matrix:
  include:

    # GCC 9
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - CMAKE_OPTNS="-D Template_ENABLE_COVERAGE:BOOL=TRUE
                       -D CODE_COVERAGE=ON
                       -D CMAKE_BUILD_TYPE=Debug"
      install:    
        # first we create a directory for the CMake binaries
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
        # we use wget to fetch the cmake binaries
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0.tar.gz
        # extract the binaries; the output here is quite lengthy,
        # so we swallow it to not clutter up the travis console
        - tar -xvf cmake-3.17.0.tar.gz > /dev/null
        - mv cmake-3.17.0 cmake-install
        # add both the top-level directory and the bin directory from the archive
        # to the system PATH. By adding it to the front of the path we hide the
        # preinstalled CMake with our own.
        - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
        # don't forget to switch back to the main build directory once you are done
        - cd ${TRAVIS_BUILD_DIR}

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake $CMAKE_OPTNS .
  - cmake --build . -- -j2 
  - ctest -j2 --output-on-failure

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info 
  # filter out system and catch headers
  - lcov --remove coverage.info '/usr/*' 'tests/catch.hpp' --output-file coverage.info 
  # debug info
  - lcov --list coverage.info 
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
